// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/lk2023060901/xdooria-proto-internal/game"
	"github.com/lk2023060901/xdooria/app/game/internal/dao"
	"github.com/lk2023060901/xdooria/app/game/internal/handler"
	"github.com/lk2023060901/xdooria/app/game/internal/manager"
	"github.com/lk2023060901/xdooria/app/game/internal/metrics"
	"github.com/lk2023060901/xdooria/app/game/internal/repository"
	"github.com/lk2023060901/xdooria/app/game/internal/service"
	"github.com/lk2023060901/xdooria/pkg/app"
	"github.com/lk2023060901/xdooria/pkg/database/postgres"
	"github.com/lk2023060901/xdooria/pkg/database/redis"
	"github.com/lk2023060901/xdooria/pkg/logger"
	"github.com/lk2023060901/xdooria/pkg/network/grpc/server"
	"github.com/lk2023060901/xdooria/pkg/prometheus"
	"github.com/lk2023060901/xdooria/pkg/registry"
	"github.com/lk2023060901/xdooria/pkg/registry/etcd"
	"github.com/lk2023060901/xdooria/pkg/router"
)

// Injectors from wire.go:

func InitApp(cfg *Config, l logger.Logger) (app.Application, func(), error) {
	v := provideAppOptions(cfg, l)
	baseApp := app.NewBaseApp(v...)
	config := provideGRPCServerConfig(cfg)
	v2 := provideGRPCServerOptions()
	serverServer, err := server.New(config, v2...)
	if err != nil {
		return nil, nil, err
	}
	router := provideRouter()
	postgresConfig := providePostgresConfig(cfg)
	client, err := postgres.New(postgresConfig)
	if err != nil {
		return nil, nil, err
	}
	metricsConfig := provideMetricsConfig(cfg)
	gameMetrics, err := metrics.New(metricsConfig)
	if err != nil {
		return nil, nil, err
	}
	roleDAO := dao.NewRoleDAO(client, l, gameMetrics)
	redisConfig := provideRedisConfig(cfg)
	redisClient, err := redis.NewClient(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	cacheDAO := dao.NewCacheDAO(redisClient, l, gameMetrics)
	roleManager := manager.NewRoleManager(l, roleDAO, cacheDAO, gameMetrics)
	sceneManager := manager.NewSceneManager(l)
	sceneService := service.NewSceneService(l, roleManager, sceneManager, gameMetrics)
	messageService := service.NewMessageService(l, router, roleManager, sceneService, gameMetrics)
	sessionManager := manager.NewSessionManager(l, cacheDAO)
	roleService := service.NewRoleService(l, roleManager, sessionManager, roleDAO, gameMetrics)
	gameHandler := handler.NewGameHandler(l, roleService, messageService)
	dollDAO := dao.NewDollDAO(client, l, gameMetrics)
	gachaDAO := dao.NewGachaDAO(client, l, gameMetrics)
	bagDAO := dao.NewBagDAO(client, l, gameMetrics)
	playerRepository := repository.NewPlayerRepository(dollDAO, gachaDAO, bagDAO, cacheDAO, l)
	dollService := service.NewDollService(l, playerRepository, gameMetrics)
	dollHandler := handler.NewDollHandler(l, dollService)
	dropService := service.NewDropService(l)
	bagService := service.NewBagService(l, playerRepository)
	gachaService := service.NewGachaService(l, playerRepository, dropService, dollService, bagService)
	gachaHandler := handler.NewGachaHandler(l, gachaService)
	smeltService := service.NewSmeltService(l, playerRepository, dropService, dollService, bagService)
	smeltHandler := handler.NewSmeltHandler(l, smeltService)
	prometheusConfig := providePrometheusConfig(cfg)
	prometheusClient, err := prometheus.New(prometheusConfig)
	if err != nil {
		return nil, nil, err
	}
	etcdConfig := provideRegistryConfig(cfg)
	registrar, err := etcd.NewRegistrar(etcdConfig)
	if err != nil {
		return nil, nil, err
	}
	reporter, err := provideMetricsReporter(gameMetrics, registrar, l)
	if err != nil {
		return nil, nil, err
	}
	resolver, err := etcd.NewResolver(etcdConfig)
	if err != nil {
		return nil, nil, err
	}
	gameConfigConfig := provideGameConfigConfig(cfg)
	configDAO, err := dao.NewConfigDAO(gameConfigConfig, baseApp)
	if err != nil {
		return nil, nil, err
	}
	appComponents := provideAppComponents(baseApp, serverServer, messageService, gameHandler, dollHandler, gachaHandler, smeltHandler, prometheusClient, gameMetrics, reporter, registrar, resolver, client, redisClient, configDAO, cfg, v)
	application := app.InitApp(baseApp, appComponents)
	return application, func() {
	}, nil
}

// wire.go:

// providePostgresConfig 提供 PostgreSQL 配置
func providePostgresConfig(cfg *Config) *postgres.Config {
	return &cfg.Database
}

// provideRedisConfig 提供 Redis 配置
func provideRedisConfig(cfg *Config) *redis.Config {
	return &cfg.Redis
}

// provideGameConfigConfig 提供游戏配置表加载配置
func provideGameConfigConfig(cfg *Config) *dao.GameConfigConfig {
	return &dao.GameConfigConfig{
		DataDir: cfg.GameConfig.DataDir,
	}
}

// provideGRPCServerConfig 提供 gRPC Server 配置
func provideGRPCServerConfig(cfg *Config) *server.Config {
	return &cfg.GRPC
}

// provideGRPCServerOptions 提供 gRPC Server 选项
func provideGRPCServerOptions() []server.Option {
	return nil
}

// provideRouter 提供消息路由器
func provideRouter() router.Router {
	return router.New()
}

// providePrometheusConfig 提供 Prometheus 配置
func providePrometheusConfig(cfg *Config) *prometheus.Config {
	return &cfg.Prometheus
}

// provideRegistryConfig 提供服务注册配置
func provideRegistryConfig(cfg *Config) *etcd.Config {
	return &cfg.Registry
}

// provideMetricsConfig 提供指标配置
func provideMetricsConfig(cfg *Config) *metrics.Config {
	return &cfg.Metrics
}

// provideMetricsReporter 提供指标上报器
func provideMetricsReporter(
	m *metrics.GameMetrics,
	registrar registry.Registrar,
	l logger.Logger,
) (*metrics.Reporter, error) {
	cfg := m.GetConfig()
	return metrics.NewReporter(&cfg.Reporter, m, registrar, l)
}

// provideAppOptions 提供应用选项
func provideAppOptions(cfg *Config, l logger.Logger) []app.Option {
	return []app.Option{app.WithName(app.AppName), app.WithLogger(l), app.WithLogConfig(&cfg.Log), app.WithNamedLoggers(cfg.Loggers)}
}

// provideAppComponents 提供应用组件
func provideAppComponents(
	baseApp *app.BaseApp,
	grpcServer *server.Server,
	messageSvc *service.MessageService,
	gameHandler *handler.GameHandler,
	dollHandler *handler.DollHandler,
	gachaHandler *handler.GachaHandler,
	smeltHandler *handler.SmeltHandler,
	promClient *prometheus.Client,
	gameMetrics *metrics.GameMetrics,
	reporter *metrics.Reporter,
	registrar *etcd.Registrar,
	resolver *etcd.Resolver,
	postgresClient *postgres.Client,
	redisClient *redis.Client,
	_ *dao.ConfigDAO,
	cfg *Config,
	opts []app.Option,
) app.AppComponents {
	gamepb.RegisterGameServiceServer(grpcServer.GetGRPCServer(), gameHandler)
	router2 := messageSvc.RoleRouter()
	dollHandler.RegisterHandlers(router2)
	gachaHandler.RegisterHandlers(router2)
	smeltHandler.RegisterHandlers(router2)

	_ = gameMetrics.Register(promClient.Registry())

	reporter.Start()

	serviceStarter := &serviceRegistrar{
		registrar:   registrar,
		serviceName: cfg.Registry.ServiceName,
		serviceAddr: cfg.Registry.ServiceAddr,
		logger:      baseApp.AppLogger(),
	}

	return app.AppComponents{
		Servers: []app.Server{
			grpcServer,
			serviceStarter,
		},
		Closers: []app.Closer{
			&metricsCloser{
				reporter:    reporter,
				gameMetrics: gameMetrics,
			},
			promClient,
			&registrarCloser{registrar: registrar},
			resolver,
			&postgresCloser{client: postgresClient},
			redisClient,
		},
	}
}

// metricsCloser 指标上报器关闭器
type metricsCloser struct {
	reporter    *metrics.Reporter
	gameMetrics *metrics.GameMetrics
}

func (c *metricsCloser) Close() error {
	c.reporter.Stop()
	c.gameMetrics.Stop()
	return nil
}

// registrarCloser 服务注册器关闭器
type registrarCloser struct {
	registrar *etcd.Registrar
}

func (c *registrarCloser) Close() error {
	return c.registrar.Deregister(context.Background())
}

// postgresCloser PostgreSQL 客户端关闭器
type postgresCloser struct {
	client *postgres.Client
}

func (c *postgresCloser) Close() error {
	c.client.Close()
	return nil
}

// serviceRegistrar 服务注册启动器，实现 app.Server 接口
type serviceRegistrar struct {
	registrar   *etcd.Registrar
	serviceName string
	serviceAddr string
	logger      logger.Logger
}

func (s *serviceRegistrar) Start() error {
	info := &registry.ServiceInfo{
		ServiceName: s.serviceName,
		Address:     s.serviceAddr,
		Metadata:    make(map[string]string),
	}
	if err := s.registrar.Register(context.Background(), info); err != nil {
		s.logger.Error("failed to register service", "error", err)
		return err
	}
	s.logger.Info("service registered to etcd", "name", s.serviceName, "addr", s.serviceAddr)
	return nil
}

func (s *serviceRegistrar) Stop() error {
	return nil
}
