// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: streaming.proto

package streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	// Server Streaming: 服务端流式返回多个响应
	ListNumbers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (StreamService_ListNumbersClient, error)
	// Client Streaming: 客户端流式发送多个请求
	Sum(ctx context.Context, opts ...grpc.CallOption) (StreamService_SumClient, error)
	// Bidirectional Streaming: 双向流式通信
	Chat(ctx context.Context, opts ...grpc.CallOption) (StreamService_ChatClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) ListNumbers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (StreamService_ListNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], "/streaming.StreamService/ListNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceListNumbersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_ListNumbersClient interface {
	Recv() (*NumberResponse, error)
	grpc.ClientStream
}

type streamServiceListNumbersClient struct {
	grpc.ClientStream
}

func (x *streamServiceListNumbersClient) Recv() (*NumberResponse, error) {
	m := new(NumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) Sum(ctx context.Context, opts ...grpc.CallOption) (StreamService_SumClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], "/streaming.StreamService/Sum", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceSumClient{stream}
	return x, nil
}

type StreamService_SumClient interface {
	Send(*NumberRequest) error
	CloseAndRecv() (*SumResponse, error)
	grpc.ClientStream
}

type streamServiceSumClient struct {
	grpc.ClientStream
}

func (x *streamServiceSumClient) Send(m *NumberRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceSumClient) CloseAndRecv() (*SumResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (StreamService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[2], "/streaming.StreamService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceChatClient{stream}
	return x, nil
}

type StreamService_ChatClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type streamServiceChatClient struct {
	grpc.ClientStream
}

func (x *streamServiceChatClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceChatClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	// Server Streaming: 服务端流式返回多个响应
	ListNumbers(*ListRequest, StreamService_ListNumbersServer) error
	// Client Streaming: 客户端流式发送多个请求
	Sum(StreamService_SumServer) error
	// Bidirectional Streaming: 双向流式通信
	Chat(StreamService_ChatServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) ListNumbers(*ListRequest, StreamService_ListNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListNumbers not implemented")
}
func (UnimplementedStreamServiceServer) Sum(StreamService_SumServer) error {
	return status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedStreamServiceServer) Chat(StreamService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_ListNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).ListNumbers(m, &streamServiceListNumbersServer{stream})
}

type StreamService_ListNumbersServer interface {
	Send(*NumberResponse) error
	grpc.ServerStream
}

type streamServiceListNumbersServer struct {
	grpc.ServerStream
}

func (x *streamServiceListNumbersServer) Send(m *NumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamService_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Sum(&streamServiceSumServer{stream})
}

type StreamService_SumServer interface {
	SendAndClose(*SumResponse) error
	Recv() (*NumberRequest, error)
	grpc.ServerStream
}

type streamServiceSumServer struct {
	grpc.ServerStream
}

func (x *streamServiceSumServer) SendAndClose(m *SumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceSumServer) Recv() (*NumberRequest, error) {
	m := new(NumberRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Chat(&streamServiceChatServer{stream})
}

type StreamService_ChatServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type streamServiceChatServer struct {
	grpc.ServerStream
}

func (x *streamServiceChatServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceChatServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListNumbers",
			Handler:       _StreamService_ListNumbers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sum",
			Handler:       _StreamService_Sum_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _StreamService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
