// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: streaming/streaming.proto

package streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_ListNumbers_FullMethodName = "/streaming.StreamService/ListNumbers"
	StreamService_Sum_FullMethodName         = "/streaming.StreamService/Sum"
	StreamService_Chat_FullMethodName        = "/streaming.StreamService/Chat"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StreamService 演示三种流式 RPC
type StreamServiceClient interface {
	// Server Streaming: 服务端流式返回多个响应
	ListNumbers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NumberResponse], error)
	// Client Streaming: 客户端流式发送多个请求
	Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, SumResponse], error)
	// Bidirectional Streaming: 双向流式通信
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) ListNumbers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NumberResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_ListNumbers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListRequest, NumberResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_ListNumbersClient = grpc.ServerStreamingClient[NumberResponse]

func (c *streamServiceClient) Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, SumResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], StreamService_Sum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NumberRequest, SumResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_SumClient = grpc.ClientStreamingClient[NumberRequest, SumResponse]

func (c *streamServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[2], StreamService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_ChatClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
//
// StreamService 演示三种流式 RPC
type StreamServiceServer interface {
	// Server Streaming: 服务端流式返回多个响应
	ListNumbers(*ListRequest, grpc.ServerStreamingServer[NumberResponse]) error
	// Client Streaming: 客户端流式发送多个请求
	Sum(grpc.ClientStreamingServer[NumberRequest, SumResponse]) error
	// Bidirectional Streaming: 双向流式通信
	Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) ListNumbers(*ListRequest, grpc.ServerStreamingServer[NumberResponse]) error {
	return status.Error(codes.Unimplemented, "method ListNumbers not implemented")
}
func (UnimplementedStreamServiceServer) Sum(grpc.ClientStreamingServer[NumberRequest, SumResponse]) error {
	return status.Error(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedStreamServiceServer) Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_ListNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).ListNumbers(m, &grpc.GenericServerStream[ListRequest, NumberResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_ListNumbersServer = grpc.ServerStreamingServer[NumberResponse]

func _StreamService_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Sum(&grpc.GenericServerStream[NumberRequest, SumResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_SumServer = grpc.ClientStreamingServer[NumberRequest, SumResponse]

func _StreamService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).Chat(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_ChatServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListNumbers",
			Handler:       _StreamService_ListNumbers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sum",
			Handler:       _StreamService_Sum_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _StreamService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "streaming/streaming.proto",
}
