
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;

/**
 * 背包类型
 */
const (
    /**
     * 装扮背包
     */
    BagType_Costume = 1;
    /**
     * 道具背包
     */
    BagType_Item = 2;
    /**
     * 装备栏
     */
    BagType_Equipment = 3;
)

