
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;

/**
 * 玩偶类型
 */
const (
    /**
     * 动物
     */
    DollType_Animal = 1;
    /**
     * 人物
     */
    DollType_Human = 2;
    /**
     * 植物
     */
    DollType_Plant = 3;
    /**
     * 物品
     */
    DollType_Object = 4;
)

