
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type DropItem struct {
    Id int32
    GroupId int32
    ItemId int32
    CountMin int32
    CountMax int32
    DropValue int32
}

const TypeId_DropItem = -368217406

func (*DropItem) GetTypeId() int32 {
    return -368217406
}

func NewDropItem(_buf map[string]interface{}) (_v *DropItem, err error) {
    _v = &DropItem{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_group_id__ interface{}; if __json_group_id__, _ok_ = _buf["group_id"]; !_ok_ || __json_group_id__ == nil { err = errors.New("group_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_group_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GroupId = __x__ }}
    { var _ok_ bool; var __json_item_id__ interface{}; if __json_item_id__, _ok_ = _buf["item_id"]; !_ok_ || __json_item_id__ == nil { err = errors.New("item_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_item_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ItemId = __x__ }}
    { var _ok_ bool; var __json_count_min__ interface{}; if __json_count_min__, _ok_ = _buf["count_min"]; !_ok_ || __json_count_min__ == nil { err = errors.New("count_min error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_count_min__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CountMin = __x__ }}
    { var _ok_ bool; var __json_count_max__ interface{}; if __json_count_max__, _ok_ = _buf["count_max"]; !_ok_ || __json_count_max__ == nil { err = errors.New("count_max error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_count_max__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CountMax = __x__ }}
    { var _ok_ bool; var __json_drop_value__ interface{}; if __json_drop_value__, _ok_ = _buf["drop_value"]; !_ok_ || __json_drop_value__ == nil { err = errors.New("drop_value error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_drop_value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DropValue = __x__ }}
    return
}

