
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type DropGroup struct {
    Id int32
    DropId int32
    DropType int32
    RollCount int32
}

const TypeId_DropGroup = 1468265648

func (*DropGroup) GetTypeId() int32 {
    return 1468265648
}

func NewDropGroup(_buf map[string]interface{}) (_v *DropGroup, err error) {
    _v = &DropGroup{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_drop_id__ interface{}; if __json_drop_id__, _ok_ = _buf["drop_id"]; !_ok_ || __json_drop_id__ == nil { err = errors.New("drop_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_drop_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DropId = __x__ }}
    { var _ok_ bool; var __json_drop_type__ interface{}; if __json_drop_type__, _ok_ = _buf["drop_type"]; !_ok_ || __json_drop_type__ == nil { err = errors.New("drop_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_drop_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DropType = __x__ }}
    { var _ok_ bool; var __json_roll_count__ interface{}; if __json_roll_count__, _ok_ = _buf["roll_count"]; !_ok_ || __json_roll_count__ == nil { err = errors.New("roll_count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_roll_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RollCount = __x__ }}
    return
}

