
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;

/**
 * 道具品质
 */
const (
    /**
     * 白色
     */
    ItemQuality_White = 1;
    /**
     * 绿色
     */
    ItemQuality_Green = 2;
    /**
     * 蓝色
     */
    ItemQuality_Blue = 3;
    /**
     * 紫色
     */
    ItemQuality_Purple = 4;
    /**
     * 橙色
     */
    ItemQuality_Orange = 5;
)

