
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type ShopItemAlliance struct {
    Id int32
    ShopId int32
    ItemId int32
    CurrencyType int32
    Price int32
    Discount int32
    StockType int32
    StockLimit int32
    UnlockLevel int32
    AllianceLevelRequire int32
    AllianceContributionMin int32
}

const TypeId_ShopItemAlliance = -2032167264

func (*ShopItemAlliance) GetTypeId() int32 {
    return -2032167264
}

func NewShopItemAlliance(_buf map[string]interface{}) (_v *ShopItemAlliance, err error) {
    _v = &ShopItemAlliance{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_shop_id__ interface{}; if __json_shop_id__, _ok_ = _buf["shop_id"]; !_ok_ || __json_shop_id__ == nil { err = errors.New("shop_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_shop_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ShopId = __x__ }}
    { var _ok_ bool; var __json_item_id__ interface{}; if __json_item_id__, _ok_ = _buf["item_id"]; !_ok_ || __json_item_id__ == nil { err = errors.New("item_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_item_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ItemId = __x__ }}
    { var _ok_ bool; var __json_currency_type__ interface{}; if __json_currency_type__, _ok_ = _buf["currency_type"]; !_ok_ || __json_currency_type__ == nil { err = errors.New("currency_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_currency_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CurrencyType = __x__ }}
    { var _ok_ bool; var __json_price__ interface{}; if __json_price__, _ok_ = _buf["price"]; !_ok_ || __json_price__ == nil { err = errors.New("price error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_price__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Price = __x__ }}
    { var _ok_ bool; var __json_discount__ interface{}; if __json_discount__, _ok_ = _buf["discount"]; !_ok_ || __json_discount__ == nil { err = errors.New("discount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_discount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Discount = __x__ }}
    { var _ok_ bool; var __json_stock_type__ interface{}; if __json_stock_type__, _ok_ = _buf["stock_type"]; !_ok_ || __json_stock_type__ == nil { err = errors.New("stock_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_stock_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StockType = __x__ }}
    { var _ok_ bool; var __json_stock_limit__ interface{}; if __json_stock_limit__, _ok_ = _buf["stock_limit"]; !_ok_ || __json_stock_limit__ == nil { err = errors.New("stock_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_stock_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StockLimit = __x__ }}
    { var _ok_ bool; var __json_unlock_level__ interface{}; if __json_unlock_level__, _ok_ = _buf["unlock_level"]; !_ok_ || __json_unlock_level__ == nil { err = errors.New("unlock_level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unlock_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockLevel = __x__ }}
    { var _ok_ bool; var __json_alliance_level_require__ interface{}; if __json_alliance_level_require__, _ok_ = _buf["alliance_level_require"]; !_ok_ || __json_alliance_level_require__ == nil { err = errors.New("alliance_level_require error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_alliance_level_require__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AllianceLevelRequire = __x__ }}
    { var _ok_ bool; var __json_alliance_contribution_min__ interface{}; if __json_alliance_contribution_min__, _ok_ = _buf["alliance_contribution_min"]; !_ok_ || __json_alliance_contribution_min__ == nil { err = errors.New("alliance_contribution_min error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_alliance_contribution_min__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AllianceContributionMin = __x__ }}
    return
}

