
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type SmeltActivity struct {
    Id int32
    Name string
    StartTime string
    EndTime string
    DropId int32
}

const TypeId_SmeltActivity = 947742754

func (*SmeltActivity) GetTypeId() int32 {
    return 947742754
}

func NewSmeltActivity(_buf map[string]interface{}) (_v *SmeltActivity, err error) {
    _v = &SmeltActivity{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_start_time__ interface{}; if __json_start_time__, _ok_ = _buf["start_time"]; !_ok_ || __json_start_time__ == nil { err = errors.New("start_time error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_start_time__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.StartTime = __x__ }}
    { var _ok_ bool; var __json_end_time__ interface{}; if __json_end_time__, _ok_ = _buf["end_time"]; !_ok_ || __json_end_time__ == nil { err = errors.New("end_time error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_end_time__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.EndTime = __x__ }}
    { var _ok_ bool; var __json_drop_id__ interface{}; if __json_drop_id__, _ok_ = _buf["drop_id"]; !_ok_ || __json_drop_id__ == nil { err = errors.New("drop_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_drop_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DropId = __x__ }}
    return
}

