
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TbGlobalConfig *TbGlobalConfig
    TbItem *TbItem
    TbDoll *TbDoll
    TbDrop *TbDrop
    TbDropGroup *TbDropGroup
    TbDropItem *TbDropItem
    TbGacha *TbGacha
    TbGachaPity *TbGachaPity
    TbShopItem *TbShopItem
    TbSmeltActivity *TbSmeltActivity
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("tbglobalconfig") ; err != nil {
        return nil, err
    }
    if tables.TbGlobalConfig, err = NewTbGlobalConfig(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbitem") ; err != nil {
        return nil, err
    }
    if tables.TbItem, err = NewTbItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbdoll") ; err != nil {
        return nil, err
    }
    if tables.TbDoll, err = NewTbDoll(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbdrop") ; err != nil {
        return nil, err
    }
    if tables.TbDrop, err = NewTbDrop(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbdropgroup") ; err != nil {
        return nil, err
    }
    if tables.TbDropGroup, err = NewTbDropGroup(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbdropitem") ; err != nil {
        return nil, err
    }
    if tables.TbDropItem, err = NewTbDropItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbgacha") ; err != nil {
        return nil, err
    }
    if tables.TbGacha, err = NewTbGacha(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbgachapity") ; err != nil {
        return nil, err
    }
    if tables.TbGachaPity, err = NewTbGachaPity(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbshopitem") ; err != nil {
        return nil, err
    }
    if tables.TbShopItem, err = NewTbShopItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbsmeltactivity") ; err != nil {
        return nil, err
    }
    if tables.TbSmeltActivity, err = NewTbSmeltActivity(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


