
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type TbDrop struct {
    _dataMap map[int32]*Drop
    _dataList []*Drop
}

func NewTbDrop(_buf []map[string]interface{}) (*TbDrop, error) {
    _dataList := make([]*Drop, 0, len(_buf))
    dataMap := make(map[int32]*Drop)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDrop(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbDrop{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbDrop) GetDataMap() map[int32]*Drop {
    return table._dataMap
}

func (table *TbDrop) GetDataList() []*Drop {
    return table._dataList
}

func (table *TbDrop) Get(key int32) *Drop {
    return table._dataMap[key]
}


