
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type TbDropGroup struct {
    _dataMap map[int32]*DropGroup
    _dataList []*DropGroup
}

func NewTbDropGroup(_buf []map[string]interface{}) (*TbDropGroup, error) {
    _dataList := make([]*DropGroup, 0, len(_buf))
    dataMap := make(map[int32]*DropGroup)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDropGroup(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbDropGroup{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbDropGroup) GetDataMap() map[int32]*DropGroup {
    return table._dataMap
}

func (table *TbDropGroup) GetDataList() []*DropGroup {
    return table._dataList
}

func (table *TbDropGroup) Get(key int32) *DropGroup {
    return table._dataMap[key]
}


