
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type TbDropItem struct {
    _dataMap map[int32]*DropItem
    _dataList []*DropItem
}

func NewTbDropItem(_buf []map[string]interface{}) (*TbDropItem, error) {
    _dataList := make([]*DropItem, 0, len(_buf))
    dataMap := make(map[int32]*DropItem)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDropItem(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbDropItem{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbDropItem) GetDataMap() map[int32]*DropItem {
    return table._dataMap
}

func (table *TbDropItem) GetDataList() []*DropItem {
    return table._dataList
}

func (table *TbDropItem) Get(key int32) *DropItem {
    return table._dataMap[key]
}


