
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type TbGacha struct {
    _dataMap map[int32]*Gacha
    _dataList []*Gacha
}

func NewTbGacha(_buf []map[string]interface{}) (*TbGacha, error) {
    _dataList := make([]*Gacha, 0, len(_buf))
    dataMap := make(map[int32]*Gacha)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGacha(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbGacha{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbGacha) GetDataMap() map[int32]*Gacha {
    return table._dataMap
}

func (table *TbGacha) GetDataList() []*Gacha {
    return table._dataList
}

func (table *TbGacha) Get(key int32) *Gacha {
    return table._dataMap[key]
}


