
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type TbGlobalConfig struct {
    _dataMap map[int32]*GlobalConfig
    _dataList []*GlobalConfig
}

func NewTbGlobalConfig(_buf []map[string]interface{}) (*TbGlobalConfig, error) {
    _dataList := make([]*GlobalConfig, 0, len(_buf))
    dataMap := make(map[int32]*GlobalConfig)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGlobalConfig(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.TeamMaxMembers] = _v
        }
    }
    return &TbGlobalConfig{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbGlobalConfig) GetDataMap() map[int32]*GlobalConfig {
    return table._dataMap
}

func (table *TbGlobalConfig) GetDataList() []*GlobalConfig {
    return table._dataList
}

func (table *TbGlobalConfig) Get(key int32) *GlobalConfig {
    return table._dataMap[key]
}


