
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


type TbSmeltActivity struct {
    _dataMap map[int32]*SmeltActivity
    _dataList []*SmeltActivity
}

func NewTbSmeltActivity(_buf []map[string]interface{}) (*TbSmeltActivity, error) {
    _dataList := make([]*SmeltActivity, 0, len(_buf))
    dataMap := make(map[int32]*SmeltActivity)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSmeltActivity(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbSmeltActivity{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbSmeltActivity) GetDataMap() map[int32]*SmeltActivity {
    return table._dataMap
}

func (table *TbSmeltActivity) GetDataList() []*SmeltActivity {
    return table._dataList
}

func (table *TbSmeltActivity) Get(key int32) *SmeltActivity {
    return table._dataMap[key]
}


