
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 背包排序类型
 */
const (
    /**
     * 按类型
     */
    BagSortType_Type = 1;
    /**
     * 按品质
     */
    BagSortType_Quality = 2;
    /**
     * 按ID
     */
    BagSortType_Id = 3;
    /**
     * 按限时
     */
    BagSortType_ExpireTime = 4;
)

