
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;


import "errors"

type Doll struct {
    Id int32
    Model string
    Res string
    Voice string
    VoiceText string
    IdleAction string
    AllAction string
    Series int32
    MaxQuality int32
    IsLimited bool
    CanExchangeReal bool
    RealExchangeCost string
    StoryId int32
}

const TypeId_Doll = 2135915

func (*Doll) GetTypeId() int32 {
    return 2135915
}

func NewDoll(_buf map[string]interface{}) (_v *Doll, err error) {
    _v = &Doll{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_model__ interface{}; if __json_model__, _ok_ = _buf["model"]; !_ok_ || __json_model__ == nil { err = errors.New("model error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_model__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Model = __x__ }}
    { var _ok_ bool; var __json_res__ interface{}; if __json_res__, _ok_ = _buf["res"]; !_ok_ || __json_res__ == nil { err = errors.New("res error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_res__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Res = __x__ }}
    { var _ok_ bool; var __json_voice__ interface{}; if __json_voice__, _ok_ = _buf["voice"]; !_ok_ || __json_voice__ == nil { err = errors.New("voice error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_voice__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Voice = __x__ }}
    { var _ok_ bool; var __json_voice_text__ interface{}; if __json_voice_text__, _ok_ = _buf["voice_text"]; !_ok_ || __json_voice_text__ == nil { err = errors.New("voice_text error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_voice_text__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.VoiceText = __x__ }}
    { var _ok_ bool; var __json_idle_action__ interface{}; if __json_idle_action__, _ok_ = _buf["idle_action"]; !_ok_ || __json_idle_action__ == nil { err = errors.New("idle_action error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_idle_action__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IdleAction = __x__ }}
    { var _ok_ bool; var __json_all_action__ interface{}; if __json_all_action__, _ok_ = _buf["all_action"]; !_ok_ || __json_all_action__ == nil { err = errors.New("all_action error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_all_action__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AllAction = __x__ }}
    { var _ok_ bool; var __json_series__ interface{}; if __json_series__, _ok_ = _buf["series"]; !_ok_ || __json_series__ == nil { err = errors.New("series error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_series__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Series = __x__ }}
    { var _ok_ bool; var __json_max_quality__ interface{}; if __json_max_quality__, _ok_ = _buf["max_quality"]; !_ok_ || __json_max_quality__ == nil { err = errors.New("max_quality error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_max_quality__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MaxQuality = __x__ }}
    { var _ok_ bool; var __json_is_limited__ interface{}; if __json_is_limited__, _ok_ = _buf["is_limited"]; !_ok_ || __json_is_limited__ == nil { err = errors.New("is_limited error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_is_limited__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsLimited = __x__ }}
    { var _ok_ bool; var __json_can_exchange_real__ interface{}; if __json_can_exchange_real__, _ok_ = _buf["can_exchange_real"]; !_ok_ || __json_can_exchange_real__ == nil { err = errors.New("can_exchange_real error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_exchange_real__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanExchangeReal = __x__ }}
    { var _ok_ bool; var __json_real_exchange_cost__ interface{}; if __json_real_exchange_cost__, _ok_ = _buf["real_exchange_cost"]; !_ok_ || __json_real_exchange_cost__ == nil { err = errors.New("real_exchange_cost error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_real_exchange_cost__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.RealExchangeCost = __x__ }}
    { var _ok_ bool; var __json_story_id__ interface{}; if __json_story_id__, _ok_ = _buf["story_id"]; !_ok_ || __json_story_id__ == nil { err = errors.New("story_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_story_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StoryId = __x__ }}
    return
}

