
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 玩偶品质
 */
const (
    /**
     * 高级
     */
    DollQuality_Advanced = 1;
    /**
     * 稀有
     */
    DollQuality_Rare = 2;
    /**
     * 史诗
     */
    DollQuality_Epic = 3;
    /**
     * 隐藏
     */
    DollQuality_Hidden = 4;
)

