
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 玩偶排序类型
 */
const (
    /**
     * 收藏优先
     */
    DollSortType_Favorite = 1;
    /**
     * 品质排序
     */
    DollSortType_Quality = 2;
    /**
     * 获得时间排序
     */
    DollSortType_CreateTime = 3;
)

