
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 掉落类型
 */
const (
    DropType_FIXED = 1;
    DropType_WEIGHT = 2;
    DropType_PROBABILITY = 3;
)

