
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;


import "errors"

type GachaPity struct {
    Id int32
    GachaId int32
    TriggerCount int32
    PityDropId int32
    TargetQuality int32
    ExtraRewardType int32
    ExtraRewardId int32
}

const TypeId_GachaPity = -1488284992

func (*GachaPity) GetTypeId() int32 {
    return -1488284992
}

func NewGachaPity(_buf map[string]interface{}) (_v *GachaPity, err error) {
    _v = &GachaPity{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_gacha_id__ interface{}; if __json_gacha_id__, _ok_ = _buf["gacha_id"]; !_ok_ || __json_gacha_id__ == nil { err = errors.New("gacha_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_gacha_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GachaId = __x__ }}
    { var _ok_ bool; var __json_trigger_count__ interface{}; if __json_trigger_count__, _ok_ = _buf["trigger_count"]; !_ok_ || __json_trigger_count__ == nil { err = errors.New("trigger_count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_trigger_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TriggerCount = __x__ }}
    { var _ok_ bool; var __json_pity_drop_id__ interface{}; if __json_pity_drop_id__, _ok_ = _buf["pity_drop_id"]; !_ok_ || __json_pity_drop_id__ == nil { err = errors.New("pity_drop_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_pity_drop_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.PityDropId = __x__ }}
    { var _ok_ bool; var __json_target_quality__ interface{}; if __json_target_quality__, _ok_ = _buf["target_quality"]; !_ok_ || __json_target_quality__ == nil { err = errors.New("target_quality error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_target_quality__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TargetQuality = __x__ }}
    { var _ok_ bool; var __json_extra_reward_type__ interface{}; if __json_extra_reward_type__, _ok_ = _buf["extra_reward_type"]; !_ok_ || __json_extra_reward_type__ == nil { err = errors.New("extra_reward_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_extra_reward_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExtraRewardType = __x__ }}
    { var _ok_ bool; var __json_extra_reward_id__ interface{}; if __json_extra_reward_id__, _ok_ = _buf["extra_reward_id"]; !_ok_ || __json_extra_reward_id__ == nil { err = errors.New("extra_reward_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_extra_reward_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExtraRewardId = __x__ }}
    return
}

