
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;


import "errors"

type Gacha struct {
    Id int32
    Type int32
    Name string
    CostItem int32
    CostCount int32
    DropId int32
}

const TypeId_Gacha = 68558178

func (*Gacha) GetTypeId() int32 {
    return 68558178
}

func NewGacha(_buf map[string]interface{}) (_v *Gacha, err error) {
    _v = &Gacha{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_cost_item__ interface{}; if __json_cost_item__, _ok_ = _buf["cost_item"]; !_ok_ || __json_cost_item__ == nil { err = errors.New("cost_item error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cost_item__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CostItem = __x__ }}
    { var _ok_ bool; var __json_cost_count__ interface{}; if __json_cost_count__, _ok_ = _buf["cost_count"]; !_ok_ || __json_cost_count__ == nil { err = errors.New("cost_count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cost_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CostCount = __x__ }}
    { var _ok_ bool; var __json_drop_id__ interface{}; if __json_drop_id__, _ok_ = _buf["drop_id"]; !_ok_ || __json_drop_id__ == nil { err = errors.New("drop_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_drop_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DropId = __x__ }}
    return
}

