
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 抽卡类型
 */
const (
    /**
     * 常驻池
     */
    GachaType_Permanent = 1;
    /**
     * UP池
     */
    GachaType_UP = 2;
    /**
     * 限定池
     */
    GachaType_Limited = 3;
)

