
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 道具大类
 */
const (
    /**
     * 装扮
     */
    ItemType_Costume = 1;
    /**
     * 道具
     */
    ItemType_Item = 2;
    /**
     * 装备
     */
    ItemType_Equipment = 3;
)

