
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 道具子类
 */
const (
    /**
     * 套装
     */
    ItemSubType_CostumeSuit = 1;
    /**
     * 脸
     */
    ItemSubType_CostumeFace = 2;
    /**
     * 眼镜
     */
    ItemSubType_CostumeGlasses = 3;
    /**
     * 头饰
     */
    ItemSubType_CostumeHeaddress = 4;
    /**
     * 翅膀
     */
    ItemSubType_CostumeWing = 5;
    /**
     * 衣服
     */
    ItemSubType_CostumeClothes = 6;
    /**
     * 裤子
     */
    ItemSubType_CostumePants = 7;
    /**
     * 鞋
     */
    ItemSubType_CostumeShoes = 8;
    /**
     * 消耗品
     */
    ItemSubType_ItemConsumable = 9;
    /**
     * 材料
     */
    ItemSubType_ItemMaterial = 10;
    /**
     * 收藏
     */
    ItemSubType_ItemCollection = 11;
    /**
     * 武器
     */
    ItemSubType_EquipWeapon = 12;
    /**
     * 头盔
     */
    ItemSubType_EquipHelmet = 13;
    /**
     * 手套
     */
    ItemSubType_EquipGloves = 14;
    /**
     * 上衣
     */
    ItemSubType_EquipArmor = 15;
    /**
     * 裤子
     */
    ItemSubType_EquipPants = 16;
    /**
     * 鞋子
     */
    ItemSubType_EquipBoots = 17;
)

