
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;

/**
 * 保底奖励类型
 */
const (
    /**
     * 无额外奖励
     */
    PityRewardType_None = 0;
    /**
     * 具体道具
     */
    PityRewardType_Item = 1;
    /**
     * 掉落包
     */
    PityRewardType_Drop = 2;
)

