
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;


type TbAccount struct {
    _dataMap map[int32]*Account
    _dataList []*Account
}

func NewTbAccount(_buf []map[string]interface{}) (*TbAccount, error) {
    _dataList := make([]*Account, 0, len(_buf))
    dataMap := make(map[int32]*Account)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAccount(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbAccount{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbAccount) GetDataMap() map[int32]*Account {
    return table._dataMap
}

func (table *TbAccount) GetDataList() []*Account {
    return table._dataList
}

func (table *TbAccount) Get(key int32) *Account {
    return table._dataMap[key]
}


