
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;


type TbDoll struct {
    _dataMap map[int32]*Doll
    _dataList []*Doll
}

func NewTbDoll(_buf []map[string]interface{}) (*TbDoll, error) {
    _dataList := make([]*Doll, 0, len(_buf))
    dataMap := make(map[int32]*Doll)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDoll(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbDoll{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbDoll) GetDataMap() map[int32]*Doll {
    return table._dataMap
}

func (table *TbDoll) GetDataList() []*Doll {
    return table._dataList
}

func (table *TbDoll) Get(key int32) *Doll {
    return table._dataMap[key]
}


