
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package config;


type TbGachaPity struct {
    _dataMap map[int32]*GachaPity
    _dataList []*GachaPity
}

func NewTbGachaPity(_buf []map[string]interface{}) (*TbGachaPity, error) {
    _dataList := make([]*GachaPity, 0, len(_buf))
    dataMap := make(map[int32]*GachaPity)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGachaPity(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbGachaPity{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbGachaPity) GetDataMap() map[int32]*GachaPity {
    return table._dataMap
}

func (table *TbGachaPity) GetDataList() []*GachaPity {
    return table._dataList
}

func (table *TbGachaPity) Get(key int32) *GachaPity {
    return table._dataMap[key]
}


