
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package gameconfig;


import "errors"

type Account struct {
    Id int32
    UserName string
    Password string
}

const TypeId_Account = 487334413

func (*Account) GetTypeId() int32 {
    return 487334413
}

func NewAccount(_buf map[string]interface{}) (_v *Account, err error) {
    _v = &Account{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_user_name__ interface{}; if __json_user_name__, _ok_ = _buf["user_name"]; !_ok_ || __json_user_name__ == nil { err = errors.New("user_name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_user_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.UserName = __x__ }}
    { var _ok_ bool; var __json_password__ interface{}; if __json_password__, _ok_ = _buf["password"]; !_ok_ || __json_password__ == nil { err = errors.New("password error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_password__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Password = __x__ }}
    return
}

