// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/lk2023060901/xdooria/app/login/internal/dao"
	"github.com/lk2023060901/xdooria/app/login/internal/handler"
	"github.com/lk2023060901/xdooria/app/login/internal/manager"
	"github.com/lk2023060901/xdooria/app/login/internal/metrics"
	"github.com/lk2023060901/xdooria/app/login/internal/service"
	"github.com/lk2023060901/xdooria/component/auth"
	"github.com/lk2023060901/xdooria/pkg/app"
	"github.com/lk2023060901/xdooria/pkg/balancer"
	"github.com/lk2023060901/xdooria/pkg/logger"
	"github.com/lk2023060901/xdooria/pkg/network/framer"
	"github.com/lk2023060901/xdooria/pkg/network/session"
	"github.com/lk2023060901/xdooria/pkg/network/tcp"
	"github.com/lk2023060901/xdooria/pkg/prometheus"
	"github.com/lk2023060901/xdooria/pkg/registry"
	"github.com/lk2023060901/xdooria/pkg/registry/etcd"
	"github.com/lk2023060901/xdooria/pkg/router"
	"github.com/lk2023060901/xdooria/pkg/security"
)

// Injectors from wire.go:

func InitApp(cfg *Config, l logger.Logger) (app.Application, func(), error) {
	v := provideAppOptions(cfg, l)
	baseApp := app.NewBaseApp(v...)
	serverConfig := &cfg.TCP
	config := &cfg.Framer
	framerFramer, err := framer.New(config)
	if err != nil {
		return nil, nil, err
	}
	sessionConfig := provideSessionConfig(cfg, framerFramer)
	routerRouter := router.New()
	processor := router.NewProcessor(routerRouter)
	loginHandler := handler.NewLoginHandler(l, processor)
	server := provideSessionServer(serverConfig, sessionConfig, loginHandler)
	authManager := auth.NewManager()
	jwtConfig := &cfg.JWT
	jwtManager, err := security.NewJWTManager(jwtConfig)
	if err != nil {
		return nil, nil, err
	}
	metricsConfig := provideMetricsConfig(cfg)
	loginMetrics, err := metrics.New(metricsConfig)
	if err != nil {
		return nil, nil, err
	}
	etcdConfig := provideRegistryConfig(cfg)
	resolver, err := etcd.NewResolver(etcdConfig)
	if err != nil {
		return nil, nil, err
	}
	balancer := provideBalancer()
	loginService := service.NewLoginService(authManager, jwtManager, loginMetrics, resolver, balancer)
	localAuthenticator := manager.NewLocalAuthenticator()
	prometheusConfig := providePrometheusConfig(cfg)
	client, err := prometheus.New(prometheusConfig)
	if err != nil {
		return nil, nil, err
	}
	registrar, err := etcd.NewRegistrar(etcdConfig)
	if err != nil {
		return nil, nil, err
	}
	reporter, err := provideMetricsReporter(loginMetrics, registrar, l)
	if err != nil {
		return nil, nil, err
	}
	gameConfigConfig := provideGameConfigConfig(cfg)
	configDAO, err := dao.NewConfigDAO(gameConfigConfig, baseApp)
	if err != nil {
		return nil, nil, err
	}
	appComponents := provideAppComponents(baseApp, server, loginService, authManager, localAuthenticator, routerRouter, client, loginMetrics, reporter, registrar, resolver, configDAO, cfg, v)
	application := app.InitApp(baseApp, appComponents)
	return application, func() {
	}, nil
}

// wire.go:

// providePrometheusConfig 提供 Prometheus 配置
func providePrometheusConfig(cfg *Config) *prometheus.Config {
	return &cfg.Prometheus
}

// provideRegistryConfig 提供服务注册配置
func provideRegistryConfig(cfg *Config) *etcd.Config {
	return &cfg.Registry
}

// provideMetricsConfig 提供指标配置
func provideMetricsConfig(cfg *Config) *metrics.Config {
	return &cfg.Metrics
}

// provideGameConfigConfig 提供游戏配置表加载配置
func provideGameConfigConfig(cfg *Config) *dao.GameConfigConfig {
	return &dao.GameConfigConfig{
		DataDir: cfg.GameConfig.DataDir,
	}
}

// provideMetricsReporter 提供指标上报器
func provideMetricsReporter(
	m *metrics.LoginMetrics,
	registrar registry.Registrar,
	l logger.Logger,
) (*metrics.Reporter, error) {
	cfg := m.GetConfig()
	return metrics.NewReporter(&cfg.Reporter, m, registrar, l)
}

// provideSessionConfig 提供 Session 配置（注入 Framer）
func provideSessionConfig(cfg *Config, fr framer.Framer) *session.Config {
	sessCfg := cfg.Session
	sessCfg.Framer = fr
	return &sessCfg
}

// provideSessionServer 提供 Session Server
func provideSessionServer(
	tcpCfg *tcp.ServerConfig,
	sessCfg *session.Config,
	h session.SessionHandler,
) *session.Server {
	sessServer := session.NewServer(&session.ServerConfig{
		Session: sessCfg,
		Handler: h,
	})

	sessServer.Config().Acceptor = sessServer.ManagedAcceptor(func(handler2 session.SessionHandler) session.Acceptor {
		return tcp.NewAcceptor(tcpCfg, sessCfg, handler2)
	})
	return sessServer
}

func provideAppOptions(cfg *Config, l logger.Logger) []app.Option {
	return []app.Option{app.WithName(app.AppName), app.WithLogger(l), app.WithLogConfig(&cfg.Log), app.WithNamedLoggers(cfg.Loggers)}
}

func provideAppComponents(
	baseApp *app.BaseApp,
	sessServer *session.Server,
	loginSvc *service.LoginService,
	authMgr *auth.Manager,
	localAuth *manager.LocalAuthenticator,
	r router.Router,
	promClient *prometheus.Client,
	loginMetrics *metrics.LoginMetrics,
	reporter *metrics.Reporter,
	registrar *etcd.Registrar,
	resolver *etcd.Resolver,
	_ *dao.ConfigDAO,
	cfg *Config,
	opts []app.Option,
) app.AppComponents {

	authMgr.Register(localAuth)

	loginSvc.Init(r)

	_ = loginMetrics.Register(promClient.Registry())

	reporter.Start()

	serviceStarter := &serviceRegistrar{
		registrar:   registrar,
		serviceName: cfg.Registry.ServiceName,
		serviceAddr: cfg.TCP.Addr,
		logger:      baseApp.AppLogger(),
	}

	return app.AppComponents{
		Servers: []app.Server{
			sessServer,
			serviceStarter,
		},
		Closers: []app.Closer{
			&metricsCloser{reporter: reporter},
			promClient,
			&registrarCloser{registrar: registrar},
			resolver,
		},
	}
}

// metricsCloser 指标上报器关闭器
type metricsCloser struct {
	reporter *metrics.Reporter
}

func (c *metricsCloser) Close() error {
	c.reporter.Stop()
	return nil
}

// registrarCloser 服务注册器关闭器
type registrarCloser struct {
	registrar *etcd.Registrar
}

func (c *registrarCloser) Close() error {
	return c.registrar.Deregister(context.Background())
}

// serviceRegistrar 服务注册启动器，实现 app.Server 接口
type serviceRegistrar struct {
	registrar   *etcd.Registrar
	serviceName string
	serviceAddr string
	logger      logger.Logger
}

func (s *serviceRegistrar) Start() error {
	info := &registry.ServiceInfo{
		ServiceName: s.serviceName,
		Address:     s.serviceAddr,
		Metadata:    make(map[string]string),
	}
	if err := s.registrar.Register(context.Background(), info); err != nil {
		s.logger.Error("failed to register service", "error", err)
		return err
	}
	s.logger.Info("service registered to etcd", "name", s.serviceName, "addr", s.serviceAddr)
	return nil
}

func (s *serviceRegistrar) Stop() error {
	return nil
}

// provideBalancer 提供负载均衡器
func provideBalancer() balancer.Balancer {
	return balancer.New(balancer.RoundRobinName)
}
