// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lk2023060901/xdooria/app/login/internal/dao"
	"github.com/lk2023060901/xdooria/app/login/internal/manager"
	"github.com/lk2023060901/xdooria/app/login/internal/service"
	"github.com/lk2023060901/xdooria/component/auth"
	"github.com/lk2023060901/xdooria/pkg/app"
	"github.com/lk2023060901/xdooria/pkg/framer"
	"github.com/lk2023060901/xdooria/pkg/grpc/server"
	"github.com/lk2023060901/xdooria/pkg/logger"
	"github.com/lk2023060901/xdooria/pkg/router"
	"github.com/lk2023060901/xdooria/pkg/security"
	"github.com/xDooria/xDooria-proto-common"
)

// Injectors from wire.go:

func InitApp(cfg *Config, l logger.Logger) (app.Application, func(), error) {
	v := provideAppOptions(cfg, l)
	baseApp := app.NewBaseApp(v...)
	config := &cfg.Server
	v2 := _wireValue
	serverServer, err := server.New(config, v2...)
	if err != nil {
		return nil, nil, err
	}
	framerConfig := &cfg.Framer
	framerFramer, err := framer.New(framerConfig)
	if err != nil {
		return nil, nil, err
	}
	routerRouter := router.New()
	processor := router.NewProcessor(framerFramer, routerRouter)
	v3 := _wireValue2
	bridge := router.NewBridge(processor, v3...)
	authManager := auth.NewManager()
	jwtConfig := &cfg.JWT
	jwtManager, err := security.NewJWTManager(jwtConfig)
	if err != nil {
		return nil, nil, err
	}
	loginService := service.NewLoginService(authManager, jwtManager)
	configDAO, err := dao.NewConfigDAO(baseApp)
	if err != nil {
		return nil, nil, err
	}
	tables := configDAO.Tables
	localAuthenticator := manager.NewLocalAuthenticator(tables)
	appComponents := provideAppComponents(baseApp, serverServer, bridge, loginService, authManager, localAuthenticator, routerRouter, v)
	application := app.InitApp(baseApp, appComponents)
	return application, func() {
	}, nil
}

var (
	_wireValue  = []server.Option{}
	_wireValue2 = []router.Option{}
)

// wire.go:

func provideAppOptions(cfg *Config, l logger.Logger) []app.Option {
	return []app.Option{app.WithName(app.AppName), app.WithLogger(l), app.WithLogConfig(&cfg.Log), app.WithNamedLoggers(cfg.Loggers)}
}

func provideAppComponents(
	baseApp *app.BaseApp,
	srv *server.Server,
	bridge *router.Bridge,
	loginSvc *service.LoginService,
	authMgr *auth.Manager,
	localAuth *manager.LocalAuthenticator,
	r router.Router,
	opts []app.Option,
) app.AppComponents {

	authMgr.Register(localAuth)

	loginSvc.Init(r)
	common.RegisterCommonServiceServer(srv.GetGRPCServer(), bridge)

	return app.AppComponents{
		Servers: []app.Server{
			srv,
		},
	}
}
